## DEEP LEARNING 
### Pytorch Basic

In [60]:
import torch 
torch.cuda.is_available()

False

Dataset with pytorch

In [61]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
df = pd.read_csv('./Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [63]:
df.shape

(150, 6)

In [64]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(['Species'], axis=1).values
Y = le.fit_transform(df['Species'].values)

# Chia dữ liệu với text size = 20%
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
Y_train = torch.LongTensor(Y_train).reshape(-1, 1)
Y_test = torch.LongTensor(Y_test).reshape(-1, 1)

In [65]:
len(Y_train)

120

In [66]:
labels, counts = Y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


#### Tính đạo hàm bằng pytorch
##### Cho y =   2x^4 + x^3 + 3x^2 + 5x + 1
#### Tính y'

In [67]:
import torch

In [68]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [69]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [70]:
y.grad_fn

In [71]:
# Thực hiện lan truyền ngược và tính toán các gradient 
y.backward()

In [72]:
x.grad

tensor(93.)

##### **BTVN 1:**
            y = 5x^5 + 6x^3 + 3x + 1                

Cho biết độ dốc của đa thức trên ở điểm nào?

##### **BTVN 2:** Tạo một tensor ban đầu có giá trị là 2. Định nghĩa hàm số và tính gradient
            y = x ^ 3 + 2x ^ 2 + 5x + 1             

- Hãy tính dy/dx tại giá trị của x

- Dùng phương pháp Gradient Descent với Learning Rate Alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp 


##### **BTVN 3:** Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm tính theo công thức: 
        
            y = 3x + 5 + noise             

**Ghi chú:** --> noise là một giá trị ngẫu nhiên nhỏ

1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình.

In [73]:
# Pytorch uwith Tensor
import torch 
import numpy as np

In [74]:
torch.__version__

'2.7.1+cpu'

In [75]:
# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [76]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [77]:
print(x.dtype)

torch.int32


In [78]:
print(x.type())

torch.IntTensor


In [79]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [80]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [81]:
# Copy and sharing
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [82]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5], dtype=torch.int32)


In [83]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [84]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


##### **BTVN 4:** Giải thích 2 trường hợp ở trên

##### **BTVN 5:** 
- Bạn giúp thầy tạo tensor với
- empty
- zeros
- ones
- random
- reshape với view và view as