**Deep Learning - Tuần 2: NUMPY, PANDAS, MATPLOTLIB** 

**1.** *Numpy* là thư viện kiểu list, vì:
- Numpy nhanh.
- Có nhiều hàm tích hợp để sử dụng cho A.I

**2.** Để sử dụng numpy thì: 
        ```pip install numpy```

In [2]:
import numpy as np

In [3]:
# Thử tạo 1 danh sách list:
python_list = [1,2,3]

In [4]:
# Chuyển đổi danh sách trên thành numpy list:
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [5]:
# List trong python có thể hỗ trợ nhiều loại dữ liệu trong list:
my_list = [1,"chào",True, 2.0]

In [6]:
my_list = [1,2,3,4,5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [7]:
# Chuyển dổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4, 5])

In [8]:
# Accessing và indexing
x = np.array([1,2,3,4,5,6,7,8])   # x = np.array(range(1, 9))

In [9]:
# Lấy số 4
x[3]

np.int64(4)

In [10]:
# lấy nhiều hơn 1 phần tử
# công thức [start:and:step]
# Lấy 1 2 3 
x[0:3]

array([1, 2, 3])

- **Lấy từ 3 - 8 theo 3 cách:**
    ```x[2:8]```
    ```x[2:]```
    ```x[2:8:1]```

In [11]:
# Cách 1
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [12]:
# Cách 2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [13]:
# Cách 3 - không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [14]:
# lấy số 3 và số 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [15]:
# Đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [16]:
data = [[1, 2], [3, 4], [5, 6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# Lấy số 2
np_list[0,1]

np.int64(2)

In [18]:
# Lấy số 6
np_list[2,1]

np.int64(6)

In [19]:
# Lấy số 3 4 5 6
np_list[1:, :]


array([[3, 4],
       [5, 6]])

In [20]:
np_list[[1,2], :]

array([[3, 4],
       [5, 6]])

In [21]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [22]:
# Lấy số 1 3 5
np_list[:, 0]

array([1, 3, 5])

In [23]:
# Lấy số 1 5 theo 2 cách
np_list[[0,2], 0]

array([1, 5])

In [24]:
np_list[0::2,0]

array([1, 5])

In [25]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
# Lấy 2 6 10 14
np_list[:,1]

array([ 2,  6, 10, 14])

In [27]:
# Lấy 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [28]:
np_list[[1,2], 2]

array([ 7, 11])

In [29]:
# Lấy số 4 7 10
np_list[[0,1,2], [3,2,1]]

array([ 4,  7, 10])

In [30]:
# Lấy số 16 15 14 13
np_list[3, ::-1]


array([16, 15, 14, 13])

In [31]:
np_list[[3, 3, 3, 3],[3, 2, 1, 0]]

array([16, 15, 14, 13])

In [32]:
np_list[-1, ::-1]

array([16, 15, 14, 13])

**BTVN 1:** Cho ma trận = **[[99, 99, 99],
                        [99, 99, 99],
                        [99, 99, 99]]**
- Hãy tưởng tượng ô 99 trống
- Giả sử 1 là x
- Giả sử 0 là o
- Lấy đầu vào từ phía X và phía O luân phiên
- Nếu đầu vào từ phía x là (0, 0) thì ma trận sẽ trở thành:
**[[x , 99, 99],
[99, 99, 99],
[99, 99, 99]]**

- Nếu đầu vào từ phía o cũng là (0, 0) 
- Thông báo họ nhập lại
- Nếu không thì điền vào ma trận

- Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.

In [ ]:
import numpy as np
board = np.full((3, 3), 99) # Khởi tạo ma trận 3x3 với giá trị 99 (ô trống)

players = [1, 0]        # 1 = X, 0 = O
current_player = 0      # X đi trước

def check_winner(board, player):
    # Kiểm tra hàng
    for i in range(3):
        if np.all(board[i, :] == player):
            return True

    # Kiểm tra cột
    for i in range(3):
        if np.all(board[:, i] == player):
            return True

    # Kiểm tra đường chéo
    if np.all(np.diag(board) == player):
        return True
    if np.all(np.diag(np.fliplr(board)) == player):
        return True

    return False


while True:
    print("\nCurrent board:")
    print(board)

    player_value = players[current_player]
    player_name = "X" if player_value == 1 else "O"

    # Nhập tọa độ
    row = int(input(f"Player {player_name} - Enter row (0-2): "))
    col = int(input(f"Player {player_name} - Enter col (0-2): "))

    # Kiểm tra ô trống
    if board[row, col] != 99:
        print("Ô đã được đánh, vui lòng nhập lại!")
        continue

    # Điền giá trị vào ma trận
    board[row, col] = player_value

    # Kiểm tra thắng
    if check_winner(board, player_value):
        print("\nFinal board:")
        print(board)
        print(f"🎉 Player {player_name} wins!")
        break

    # Chuyển lượt
    current_player = 1 - current_player


---

**BTVN 2:** Cho y = [
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
                ]
- Lấy số *4*, *5* và *6*
- Lấy số *2* và *5*
- Lấy số *3* và *4*
- Lấy số *9*, *6* và *3*

In [ ]:
import numpy as np

y = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Lấy số 4, 5, 6
y[1, :]

## Lấy số 2 và 5
y[:, 1]

## Lấy số 3 và 4
np.array([y[0, 2], y[1, 0]])

## Lấy số 9, 6 và 3
y[::-1, 2]


array([3, 4])

**BTVN 3:** Cho x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**1.** Xuất ra các giá trị chẵn sử dụng *if*.

**2.** Xuất ra các giá trị chẵn sử dụng *list comprehension*.

In [38]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = []

for i in x:
    if i % 2 == 0:
        even_numbers.append(i)

print(even_numbers)

# Sử dụng hàm lệnh list comprehension
even_numbers = [i for i in x if i % 2 == 0]
print(even_numbers)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


---

In [ ]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
idx = [ True, False,  True, False,  True, False,  True, False,  True,
       False]
np_x[idx]

array([0, 2, 4, 6, 8])

In [ ]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

---

**BTVN 4:** Tạo một mảng numpy có kích thước 150 x 5. 
- Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm: `[chiều cao, cân nặng, tuổi, lương và điểm trung bình]`
- Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là X và cột cuối cùng thành Y.

- Tách X thành X_train và X_test, trong đó X_train chứa 70% dữ liệu.
- Tách Y thành Y_train và Y_test, trong đó Y_train cũng chứa 70% dữ liệu.

- Tạo 10 tập dữ liệu X_train không chồng chéo nhau.

In [39]:
import numpy as np

# Giả sử dữ liệu ngẫu nhiên
data = np.random.rand(150, 5)

X = data[:, :4]   # 4 cột đầu
Y = data[:, 4]    # cột cuối

split_index = int(0.7 * len(X))  # 70% của 150 = 105

X_train = X[:split_index]
X_test  = X[split_index:]

Y_train = Y[:split_index]
Y_test  = Y[split_index:]

X_train_splits = np.array_split(X_train, 10)

print(len(X_train_splits))        # 10
print(X_train_splits[0].shape)    # (~11, 4)


10
(11, 4)
